version: '3.5'

services:
  php-apache:
   container_name: brubi-php-apache
   build: .
   # environment:
   #   POSTGRES_USER: ecasenka
   #   POSTGRES_PASSWORD: EcasenkaApp0909
   #   POSTGRES_DB: postgres
   #   PGDATA: /data/postgres
   volumes:
     - ./web:/var/www/html
   ports:
     - "8008:80"
   networks:
     - brubi
   restart: no

networks:
  brubi:
    driver: bridge
